### ISSUE TITLE
Update container-selinux references to docker-selinux

### ISSUE THREAD

**Issue by mopsfelder** [open-power-host-os/versions#102]
The commit 3ddc526c3f7985789d869567994ddf890490c5c5 "Change docker secondary sources to git repositories" changed `docker-selinux` to `container-selinux`.

The actual package name is `docker-selinux`.

**Comment by olavphibm** [comment]
The package name changed to `container-selinux` in Fedora 24, and its repository (https://github.com/projectatomic/docker-selinux.git) redirects to the new name,
We should update our spec file to reflect that.

**Comment by fabianorosas** [comment]
Can we close this?
