### ISSUE TITLE
SPEC file contains hardcoded commit id

### ISSUE THREAD

**Issue by mfoliveira** [open-power-host-os/versions#148]
Hello guys,

May the `%commit` macro in the `kernel.spec` file (at least) be defined in a dynamic way (e.g., environment variable, set by `host_os.py`), please?

I spent some time debugging `host_os.py` and its relation with `versions.git` (plus several kernel package builds time..) to find out that the commit ID in `versions.git` was indeed picked up, but the kernel packages _filenames_ used a _different_ commit ID (hardcoded in `kernel.spec`).

```
%global commit          b0bad18237cef1541a5d98067a4008772a80f724
```

That should automatically reflect the commit defined in the `yaml` file, as users would expect.

Thank you!

**Comment by olavphibm** [comment]
Hi @mfoliveira, we currently have a command (`host_os.py update-versions`) that is executed on every weekly and nightly build which updates the packages to the latest upstream version and updates the commit ID in both the YAML and spec files. I do understand, however, that when manually modifying the commit ID it is confusing and error-prone to have it in two separate places.
We currently have no means of dynamically filling the spec file when the build is executed and doing so will require some significant changes in our scripts. I believe this will improve other aspects of the build process too, so we'll probably discuss how to implement this soon.
Thank you for the comment!

**Comment by mfoliveira** [comment]
Hi @olavphibm 

> We currently have no means of dynamically filling the spec file when the build is executed [snip]

I was thinking more of setting it to an environment variable, so the file content needs no change, but the RPM build processes defines that somehow (e.g., like other RPM macros), and then `host_os.py` is modified to pass the right/commit value to that environment variable when building.

Is that an option?

**Comment by olavphibm** [comment]
We could pass those variables to the command line with `--define`, for example. I just don't want to treat the commit ID as a special case and give a little thought on how we're gonna determine which YAML variables will be passed to the `rpmbuild` command as variables.

**Comment by mfoliveira** [comment]
Cool. I see. Thanks!

**Comment by olavphibm** [comment]
@mfoliveira We've removed commit IDs from spec files with PRs https://github.com/open-power-host-os/builds/pull/224 and https://github.com/open-power-host-os/versions/pull/151, leaving them only in the YAML files. They are now passed dynamically to `rpmbuild`.

**Comment by mfoliveira** [comment]
that's great! thanks, Olav.
